package com.threemail.android.sync

import android.content.Context
import androidx.work.ListenableWorker
import androidx.work.WorkerFactory
import androidx.work.WorkerParameters
import com.threemail.android.data.crypto.AutocryptLearner
import com.threemail.android.data.crypto.MailPgpOutbound
import com.threemail.android.data.local.dao.MessageFlagDao
import com.threemail.android.data.remote.MailRemoteFactory
import com.threemail.android.data.repository.AccountRepository
import com.threemail.android.data.repository.CalendarRepository
import com.threemail.android.data.repository.CalendarSourceRepository
import com.threemail.android.data.repository.MailActions
import com.threemail.android.data.repository.MailRepository
import com.threemail.android.data.repository.OutboxRepository
import com.threemail.android.data.settings.SettingsRepository
import com.threemail.android.notifications.NotificationHelper
import javax.inject.Inject
import javax.inject.Provider

/**
 * Manually assembles each of 3mail's [androidx.work.CoroutineWorker]
 * subclasses by `className`.
 *
 * # Rationale
 *
 * The canonical Hilt + WorkManager wiring is
 * `@HiltWorker` + `@AssistedInject` on the worker + the project's
 * [com.threemail.android.ThreeMailApplication] implementing
 * `Configuration.Provider` to feed a generated `HiltWorkerFactory`
 * into the WorkManager `Configuration`. In that flow the
 * `androidx.hilt:hilt-compiler` annotation processor scans every
 * `@HiltWorker` class at KSP time and emits a multibinding entry that
 * `HiltWorkerFactory.createWorker()` later looks up.
 *
 * This project pins KSP 2.3.10 and the latest published
 * `androidx.hilt:hilt-work` artifact is 1.4.0. The compiler shipped
 * in 1.4.0 was built against the KSP1 API and silently skips
 * generating both the `*_AssistedFactory` classes and the
 * multibinding entries when run under KSP2. The symptom downstream
 * was [HiltWorkerFactory.createWorker] returning null for every
 * worker, which made WorkManager's
 * [androidx.work.WorkerFactory.createWorkerWithDefaultFallback]
 * drop down to `ReflectiveWorkerFactory`, which then crashed with
 *
 * ```
 * java.lang.NoSuchMethodException: <fqcn>.<init>
 *     [class android.content.Context, class androidx.work.WorkerParameters]
 * ```
 *
 * for every worker instantiation, including [MailSyncWorker],
 * [CalendarSyncWorker], [SendMailWorker], and [TrashCleanupWorker].
 *
 * We considered three fixes and landed here because the alternatives
 * had hard dependencies we couldn't satisfy on the current toolchain:
 *
 *  1. **Revert KSP2 (`ksp.useKSP2=false`).** KSP 2.3.10 dropped the
 *     KSP1 backend entirely, so this option is no longer selectable.
 *
 *  2. **Bump androidx.hilt:hilt-work to 1.5.0+.** Local Maven
 *     inspection and the AndroidX release cadence confirm 1.5.0 has
 *     never been published; 1.4.0 is the latest stable.
 *
 *  3. **This factory.** Trade the `@HiltWorker`-based automatic
 *     multibinding for an explicit dispatch. Each worker's deps are
 *     pulled through a Dagger `Provider<T>` so the singleton graph is
 *     still the source of truth, but the dependency injection is
 *     spelled out in Kotlin instead of being generated by a compiler
 *     that has historically been brittle across KSP1↔KSP2 boundary
 *     changes.
 *
 * The four [androidx.work.CoroutineWorker] subclasses each take their
 * own deps as plain `val` constructor parameters - no
 * `@AssistedInject`, no `@HiltWorker`, no `dagger.assisted.*`. This
 * factory is the only place that knows how to route
 * `workManagerConfiguration`'s `(class, deps)` request onto the
 * matching constructor call.
 *
 * # Adding a new worker
 *
 * 1. Declare the worker with a plain `(Context, WorkerParameters,
 *    ...deps)` constructor (call passed-in deps `accountRepository`,
 *    etc. to match the convention below).
 * 2. Add a new field here for any *new* dep that didn't already feed
 *    one of the four existing workers (otherwise just pass through).
 * 3. Add the `when (workerClassName)` arm.
 */
class ThreeMailWorkerFactory @Inject constructor(
    private val accountRepository: Provider<AccountRepository>,
    private val mailRepository: Provider<MailRepository>,
    private val settingsRepository: Provider<SettingsRepository>,
    private val notificationHelper: Provider<NotificationHelper>,
    private val mailRemoteFactory: Provider<MailRemoteFactory>,
    private val calendarRepository: Provider<CalendarRepository>,
    private val calendarSourceRepository: Provider<CalendarSourceRepository>,
    private val outboxRepository: Provider<OutboxRepository>,
    private val mailActions: Provider<MailActions>,
    private val mailPgpOutbound: Provider<MailPgpOutbound>,
    private val messageFlagDao: Provider<MessageFlagDao>,
    private val autocrLearner: Provider<AutocryptLearner>
) : WorkerFactory() {

    override fun createWorker(
        appContext: Context,
        workerClassName: String,
        workerParameters: WorkerParameters
    ): ListenableWorker? = when (workerClassName) {
        MailSyncWorker::class.java.name -> MailSyncWorker(
            appContext,
            workerParameters,
            accountRepository.get(),
            mailRepository.get(),
            settingsRepository.get(),
            notificationHelper.get(),
            mailRemoteFactory.get(),
            autocrLearner.get()
        )
        CalendarSyncWorker::class.java.name -> CalendarSyncWorker(
            appContext,
            workerParameters,
            accountRepository.get(),
            calendarRepository.get(),
            calendarSourceRepository.get()
        )
        SendMailWorker::class.java.name -> SendMailWorker(
            appContext,
            workerParameters,
            outboxRepository.get(),
            accountRepository.get(),
            mailRemoteFactory.get(),
            mailPgpOutbound.get(),
            messageFlagDao.get()
        )
        TrashCleanupWorker::class.java.name -> TrashCleanupWorker(
            appContext,
            workerParameters,
            accountRepository.get(),
            mailRepository.get(),
            mailActions.get(),
            notificationHelper.get()
        )
        else -> throw IllegalArgumentException(
            "ThreeMailWorkerFactory has no dispatch arm for worker class '$workerClassName'. " +
                "Add one to the `when` block above (see class KDoc)."
        )
    }
}
